# Generated by Django 4.2.3 on 2023-08-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuarios', '0003_alter_usuario_nome'),
        ('app_cadastro_usuarios', '0004_modify_db'),
    ]

    operations = [
    ]
